# Generated by Django 3.2.6 on 2021-09-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
                ('primary_camera', models.IntegerField()),
                ('secondary_camera', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('coverphoto', models.ImageField(upload_to='')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='user_enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
