# Generated by Django 3.2.8 on 2021-10-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_alter_heloo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='primary_camera',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='ram',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='rom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='secondary_camera',
            field=models.CharField(max_length=20),
        ),
    ]
