# Generated by Django 3.2.8 on 2021-10-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color_fan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorfan',
            name='primary_camera',
        ),
        migrations.RemoveField(
            model_name='colorfan',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='colorfan',
            name='rom',
        ),
        migrations.RemoveField(
            model_name='colorfan',
            name='secondary_camera',
        ),
    ]
