# Generated by Django 3.2.8 on 2021-10-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='primary_camera',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='rom',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='secondary_camera',
        ),
    ]
