# Generated by Django 3.2.6 on 2021-10-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_user_enquiry1'),
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('ssd', models.IntegerField()),
                ('hdd', models.IntegerField()),
                ('pgeneration', models.IntegerField()),
                ('screensize', models.IntegerField()),
                ('processor', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('coverphoto', models.ImageField(upload_to='')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='mobile',
        ),
    ]
