# Generated by Django 3.2.6 on 2021-10-04 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laptop', '0003_auto_20211002_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=20)),
                ('priceo', models.IntegerField()),
                ('coverphotoo', models.ImageField(upload_to='')),
                ('dateorder', models.DateTimeField(default=None, null=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
